export const countryTerms = {
  'Bahrain': 'The central bank of the Kingdom of Bahrain (\'Bahrain\') has not approved the Issuer or the Offering, and no submission has been made to them to do so. All applications from Subscribers in the Token should be received and allotted from outside Bahrain. The Issuer has not made nor has provided or shall provide any invitation to the public in Bahrain to invest in the PLY Tokens in the Issuer and this Prospectus shall accordingly not be distributed to the public in Bahrain.',
  'Bermuda': 'This Prospectus refers only to PLY Tokens being offered to Subscribers on a private basis and who shall be required tyo satisfy criteria outlined in this Prospectus. None of the Prospectus, the Offering or the Issuer has been subject to nor has has received approval from the Bermuda Monetary Authority or the company registrar in Bermuda and no statement to the contrary, express or implied, is permitted or authorized to be represented. Accordingly, the PLY Tokens may only be offered and sold in Bermuda if strictly in compliance with the terms and provisions of the Investment Business Act 2003 (as amended) of Bermuda. \n' +
  '\n' +
  'Engaging in activity or activities involving the promotion, marketing and/or selling of PLY Tokens in Bermuda pursuant to this Offering to persons located in Bermuda may be deemed under Bermuda law and securities regulations to be carrying on business in Bermuda. Further, non-Bermudian persons may not carry on or engage in any trade or Business in Bermuda unless such persons are authorized to do so under applicable Bermuda legislation. ',
  'Cayman Islands': 'This Prospectus does not represent any form of invitation to the public in the Cayman Islands to become a Subscriber to PLY Tokens, interests in the Fund or Issuer. Neither shall any selling agent nor the Issuer be permitted to sell to members of the public in the Cayman Islands PLY Tokens, interests in the Issuer of Fund or any other form of interests and securities from a place of business in the territory of the Cayman Islands.',
  'France': 'Qualified investors and/or restricted circle of subscribers within the meaning of article l. 411-2, ii of the French code monétaire et financier may take part in this Offering and become Subscribers of the PLY tokens for their own account.  \n' +
  '\n' +
  'This Prospectus has not been submitted to, or approved by, the Autorité des marchés financiers in France, and the Issuer has no intention to do such in the future. This Offering of Tokens is not open to the public in France and therefore may not be distributed or disseminated, directly or indirectly, to the public in France. The meaning of the phrase public in this context means the meaning provided under article l. 411-1 of the French code monétaire et financier. ',
  'Germany': 'This Prospectus is not deemed to be nor should be considered to be a securities prospectus within the meaning of the German Securities Prospectus Act. This Prospectus is not an investment product prospectus within the meaning of the German Investment Product Act, and accordingly this Prospectus has not been nor will be filed with the German federal financial supervisory authority. The federal republic of Germany has not received filing of this Prospectus in any capacity and it is not intended that they will in the future. \n' +
  '\n' +
  'Unless an express exemption from compliance with the public offering laws, regulations and restrictions under the German Securities Prospectus Act and the Investment Product Act may apply, this Prospectus shall not and may not be made available to the public of Germany or offered for distribution and consideration for investment by the public in Germany.',
  'Guernsey': 'PLY tokens are prohibited from being offered to the public in Guernsey, and shall not be offered accordingly. Persons whom are resident in Guernsey may apply for PLY tokens in the Issuer pursuant to private placement arrangements. This Prospectus has not been filed with the Guernsey Financial Services Commission pursuant to any relevant legislation and no authorizations in respect of the relevant laws and acts governing or issued by the Guernsey Financial Services Commission have been sought or attained. ',
  'Hong Kong': 'No regulatory authority in Hong Kong has reviewed or approved this Prospectus. This Offering is not to be offered to the public in Hong Kong. The Issuer does not intend for this Offering to be promoted or made available to the public in Hong Kong. Accordingly, PLY Tokens have not been and shall not be offered or sold in Hong Kong, by means of any document or process other than: \n' +
  '\n' +
  '(i) in accordance with the Securities and Futures Ordinance (chapter 571 of the laws of Hong Kong) (the ‘SFO’), to ‘professional investors’ as defined therein, and any rules made under the SFO; or \n' +
  '\n' +
  '(ii) where this Prospectus document is otherwise not defined as a ‘prospectus’ as defined in the Companies (Winding Up and Miscellaneous Provisions) Ordinance (chapter 32, of the laws of Hong Kong); or\n' +
  '\n' +
  '(iii) in other circumstances where this Prospectus does not constitute an offer to the public within the meaning of the Companies (Winding Up and Miscellaneous Provisions) Ordinance of the laws of Hong Kong.\n' +
  '\n' +
  'Further, in compliance with the rulings of the SFO, to the extent that the intention is to provide access or allow review of this Prospectus by the public of Hong Kong, no person may issue or have in its possession for the purposes of issue, whether in Hong Kong or elsewhere, any promotional material, advertisement, invitation or document relating to the offer or these PLY Tokens except if a valid exemption exists and/or such person or entity is permitted to do so under the securities laws of Hong Kong; and other than in the context and with respect to the interests in the Issuer being offered and intended to be disposed of by persons outside of Hong Kong OR only to \'professional investors as defined in the SFO and any rules made under that ordinance.\n' +
  '\n' +
  'This Prospectus and all information and other documentation it refers and relates to herein may not be used other than by the person to whom it is addressed and lawfully issued to, and the Issuer shall only accept a subscription for interests in the Issuer from Subscribers being directly such addressed persons. This Prospectus and the information contained herein, as well as all other documentation it refers and relates to herein, may not be reproduced in any form or relayed, disseminated, revealed or transferred to any person in Hong Kong. ',
  'India': 'PLY Tokens are not being offered for sale or subscription to the public in India, but are instead only and exclusively being privately placed with a limited number of sophisticated investors; prospective Subscribers must seek their own private legal and professional financial and investment advice as to whether they are entitled to subscribe for the PLY Tokens and it is bestowed upon them to comply with all relevant Indian laws in this respect. \n' +
  '\n' +
  'This Prospectus has not been filed, submitted to or authorized by the Reserve Bank of India, Securities and Exchange Board of India, Forward Market Commission India (FMC), PFRDA under the Finance Ministry or the Insurance Regulatory and Development Authority, nor any other financial regulatory body in India. This Prospectus accordingly does not constitute any offer to sell, buy or transfer PLY Tokens from any person other than to the person to whom this Prospectus has been made available to by the Issuer or the Issuer’s authorized agent, and provided such person is validly and legally able to acquire PLY Tokens in accordance with the terms of this Prospectus. This Prospectus is not and should not be construed as a ‘prospectus’ as defined under the laws and financial regulations of the India. ',
  'Japan': 'The PLY Tokens and this Offering, as defined and described in this Prospectus, have not been submitted to or disclosed pursuant to the securities exchange law of Japan (law no.25 of 1948 as amended), and may not be.\n' +
  '\n' +
  'Any prospective Subscriber of a Token agrees that they are prevented from and therefore shall not re-transfer or re-assign such Tokens to any person or entity other than those that are non-residents of Japan, with the exception of the existence and relevant, valid appliance of a private placement exemption from the otherwise required registration of, and otherwise in compliance with, Japan securities exchange law as well as the other relevant laws and regulations of Japan (with the exception of the case of re-transfer or re-assignment of the Tokens held by such Subscriber to one person or entity through one, single transaction of all such Tokens so acquired by such Subscriber). \n' +
  '\n' +
  'The PLY tokens are not available to the public in Japan and may not be marketed or promoted to the public in Japan. The Tokens are being offered to a limited number of qualified institutional subscribers only (as defined in the securities exchange law of Japan) and/or a small number of non-institutional Subscribers. All PLY Tokens Subscribers must and shall comply with and meet the regulations pursuant to the private placement exemption from the registration requirements of the Japan securities exchange law and other relevant Laws. This Prospectus is confidential and is intended solely for..\n' +
  '\n' +
  '\n' +
  'The PLY Tokens and this Offering, as defined and described in this Prospectus, have not been submitted to or disclosed pursuant to the securities exchange law of Japan (law no.25 of 1948 as amended), and may not be.\n' +
  '\n' +
  'Any prospective Subscriber of a Token agrees that they are prevented from and therefore shall not re-transfer or re-assign such Tokens to any person or entity other than those that are non-residents of Japan, with the exception of the existence and relevant, valid appliance of a private placement exemption from the otherwise required registration of, and otherwise in compliance with, Japan securities exchange law as well as the other relevant laws and regulations of Japan (with the exception of the case of re-transfer or re-assignment of the Tokens held by such Subscriber to one person or entity through one, single transaction of all such Tokens so acquired by such Subscriber). \n' +
  '\n' +
  'The PLY tokens are not available to the public in Japan and may not be marketed or promoted to the public in Japan. The Tokens are being offered to a limited number of qualified institutional subscribers only (as defined in the securities exchange law of Japan) and/or a small number of non-institutional Subscribers. All PLY Tokens Subscribers must and shall comply with and meet the regulations pursuant to the private placement exemption from the registration requirements of the Japan securities exchange law and other relevant Laws. This Prospectus is confidential and is intended solely for the use of its recipient. Any duplication or redistribution of this Prospectus is prohibited. \n' +
  '\n' +
  'If requested, the recipient of this Prospectus shall return this document to the entity which provided it to them, in the event that the prospective Subscriber does not proceed with becoming a Tokenholder by entering into the Subscription Agreement or in any other manner acquiring the Tokens.\n' +
  '\n' +
  'Due to potential currency fluctuations, cryptocurrency fluctuations and/or other factors (see Section 12 herein), any Subscriber runs the potential risk of losing in part or in full their invested capital pursuant to this Offering and them becoming a Subscriber.',
  'Jersey': 'PLY Tokens may not be offered in Jersey unless via a valid private placement exemption, since the consent of the Jersey Financial Services Commission has expressly not been sought nor has it permitted to the circulation of an offer of PLY Tokens in Jersey pursuant to article 10 of the Control Of Borrowing (Jersey) Order 1958, as amended.',
  'Kuwait': 'Neither the Ministry of Commerce and Industry of the State of Kuwait, nor any other relevant Kuwaiti governmental agency has received or approved this Offering or Prospectus for circulation in Kuwait. Notwithstanding any other terms of content in this Prospectus, nothing herein this Prospectus constitutes, nor shall be deemed to constitute, an invitation or an offer to sell PLY Tokens; further, there is no intention of this Prospectus to invoke completion of any contract in Kuwait pertaining to this Offering. \n' +
  '\n' +
  'This Offering of PLY Tokens is provided solely on the basis that this constitutes a private placement and its public offering is restricted and governed under the laws set out in accordance with Decree Law no. 31 of 1990, as amended, entitled ‘Regulating Securities Offerings and Sales’ and Ministerial Order no. 113 of 1992, as amended, as well as under and any and all other implemented regulations, applicable laws and regulations in the State of Kuwait. ',
  'Monaco': 'Banks, licenced entities and portfolio companies duly licensed by "Comité des Etablissements de Crédit et des Entreprises d\'Investissement" and/or under law n°1.144 of July 26, 1991 and law number 1.338 of September 7, 2007 issued by the "Commission de Contrôle des Activités Financières", are the only legal entities which may offer for sale, promote or sell PLY Tokens, subject to their own procedures in accordance with compliance by them of the relevant laws of Monaco.',
  'New Zealand': 'In New Zealand, PLY Tokens may only be sold to Subscribers who either (a) habitually invest money or whose main constitution and purpose is to invest money; or (b) if not meeting the criteria of (a), shall invest a minimum subscription of US$ 500,000 for the PLY Tokens. Meeting either of these aforementioned criteria in this paragraph shall mean that, in accordance and as otherwise interpreted under New Zealand law, a registered prospectus is not required for the offer of PLY Tokens under the New Zealand Securities Act 1978. ',
  'Norway': 'The contents of this Prospectus have not been registered with the Oslo Stock Exchange or the Norwegian Company Registry, not approved by them. The Issuer is not subject to the Investment Fund Act of 1981 and, therefore, is not required to be supervised under the Financial Supervisory Authority of Norway. Furthermore, the PLY Tokens are not subject to the Securities Trading Act of 2007.',
  'Oman': 'This Prospectus is being provided to a restricted number of sophisticated investors for the purposes of enabling decision as to whether or not they should invest in and acquire PLY Tokens upon the terms set out in this Offering and subject to the restrictions set out herein this Prospectus. This Prospectus and may not be transferred, disseminated, reproduced or used for any other purpose or provided to any person or entity other than the original and intended recipient hereof. This Prospectus does not constitute a public offer of securities in the Sultanate of Oman, as defined and contemplated under the commercial companies law of Oman (Royal Decree no. 4/74) and the capital market law of Oman (Royal Decree no. 80/98) and Ministerial Decision no.1/2009 or an offer to sell or the solicitation of any offer to buy non-Omani securities in the Sultanate of Oman. \n' +
  '\n' +
  'This Prospectus is not intended to lead to the creation or entering into of any contract within the Sultanate of Oman. \n' +
  '\n' +
  'This Prospectus has not been submitted to or approved by the Capital Market Authority or the Central Bank of Oman. Accordingly, neither such institutions take any responsibility for the factual accuracy of the information contained in this Prospectus, hence they have no liability in the event of reliance on the information herein by any party. ',
  'China': '(not deemed to include Hong Kong, Macau, and Taiwan for the purposes of this Prospectus): \n' +
  '\n' +
  'Within the People\'s Republic of China, the information contained in this Prospectus does not and may not constitute an offer to sell PLY Tokens or an advertisement, invitation, provocation or solicitation of an offer to buy PLY Tokens in any manner whatsoever.   \n' +
  '\n' +
  'This Offering and Prospectus has not been submitted to or approved by the Chinese Securities and Regulatory Commission, and accordingly may not be marketed, offered or sold directly or indirectly to the public in China. Neither this Prospectus nor any supplementary documentation related to it, or information contained herein pertaining to PLY Tokens, may be supplied to the public in China. Furthermore, this Prospectus and any of the information contained herein may not be presented to the public in China in any manner in regard to the sale or offering of, or subscription to, PLY Tokens.',
  'Qatar': 'This Prospectus is provided to the intended recipient on a strictly confidential basis and any distribution of it to third parties in the State of Qatar in contravention of the terms of this Prospectus shall be on the liability solely of the disseminator. The Prospectus is intended to be for personal use only and not to be disseminated otherwise. This Prospectus does not and may not constitute any offer to do business as a bank, other institution or any other entity, in the State of Qatar, and is not open to or to be disseminated to the public.\n' +
  '\n' +
  'This Prospects is a private placement offering only and accordingly the included materials and information have not been approved or licensed by the Qatari Central Bank. No other relevant licensing authorities in the State of Qatar either have received and approved this Prospectus in any manner. Accordingly, this Prospectus, under Qatari law, does not and may not constitute a public offer of securities in the State of Qatar. ',
  'Russian Federation': 'This Prospectus and the information contained within it is not an offer, or any form of invitation to make offers, relating to the sale, purchase, exchange or similar transaction or transfer of securities or foreign financial instruments in the Russian Federation, pertaining to or for the benefit of any person or entity in the Russian Federation, with the exception of cases and circumstances permitted under Russian laws to the extent permitted. \n' +
  '\n' +
  'Information contained in this Prospectus is not to be made available to the public or persons in the Russian Federation unless and to the extent they are permitted to do so under the laws of the Russian Federation. Further, this Prospectus is not a ‘placement’ or ‘circulation’ (as defined under the securities law of the Russian Federation) of any securities, nor an advertisement of such, and nothing contained in this Prospectus is intended for ‘placement’ or ‘circulation’ in the Russian Federation, unless to the extent otherwise permitted under Russian laws. ',
  'Saudi Arabia': 'In the Kingdom of Saudi Arabia, this Prospectus may not be distributed except to persons as are permitted to receive this Prospectus and the information herein under the Offer of Securities Regulations issued by the Saudi Arabian Capital Market Authority. The Capital Market Authority has not approved this Prospectus and therefore such expressly disclaims any liability over the content and substance herein this Prospectus, its completeness, and its accuracy. Prospective Subscribers should seek legal and financial advice on this Offering before making any decision to participate or otherwise in this Offering, and the Issuer requires prospective Subscribers in all cases to have completed their own investigations and due diligence on the Offering and all aspects and entities it pertains to before making any determinations.',
  'Singapore': 'Only persons situated outside of Singapore may receive, review and consider this Offering, and the acquisition of PLY Tokens may only be acted upon by persons outside of Singapore. No person in Singapore is eligible or permitted to directly or indirectly become a Subscriber or offer to become a Subscriber to any PLY Tokens. This Offering Prospectus and all information related to it and to the PLY Tokens may not be circulated or distributed, whether directly or indirectly, to persons in Singapore.',
  'South Africa': 'This Prospectus is for the attention of and distribution to select individuals only and may not be distributed or circulated, or allowed to be distributed or circulated, to the general public in South Africa. The PLY Tokens may not be the subject of any form of public offering, nor sold or advertised in South Africa and this Prospectus may only be circulated to selected individuals and Subscribers in South Africa may only participate in this Offering in accordance with the securities laws and exemptions thereof of South Africa. No filing of this Prospectus has been made with the securities authorities or any government or semi-government body in South Africa.',
  'South Korea': 'This Prospectus does not constitute, and may not be under any circumstances construed as, an Offering of securities in South Korea. This Prospectus has not been filed with and is not therefore approved or certified in any manner whatsoever or subject to the laws of South Korea, including, without limitation, Indirect Investment Asset Management Business Law, the Securities and Exchange Act and the Foreign Exchange Transaction Act. The Issuer makes no representation that this Prospectus is therefore eligible under any such laws or acts, and any and all placement agents and intermediaries pursuant to this Offering shall not make any claim either of such eligibility to such laws and acts and regulations thereunder. The Issuer has not filed this Offering or registered this Prospectus or the PLY Tokens under the Securities and Exchange Act, Securities Investment Company Act or the Securities Investment Trust Business Act of South Korea. The PLY Tokens may not be sole, re-sold, transferred, re-transferred or in any other manner relinquished to any resident of South Korea, be such directly or indirectly.',
  'Taiwan': 'This Prospectus and Offering, and no person connected with this Prospectus including the Issuer, has authority to offer or sell PLY Tokens in Taiwan, the Republic of China (“Taiwan”). This Prospectus has not been and will and may not be registered with the Financial Supervisory Commission of Taiwan. This Offering and Prospectus may not be offered in Taiwan pursuant to the laws of the securities and exchange law of Taiwan that require a registration or approval of the Financial Supervisory Commission of Taiwan.',
  'United Arab Emirates': ' This Prospectus has not been approved by or filed with the Central Bank of the United Arab Emirates (“UAE”), Dubai Financial Services Authority or Abu Dhabi Global Market or any other regulatory authority or body in the United Arab Emirates. The PLY Tokens have not been approved or licensed by or registered with the UAE Central Bank or any other relevant licensing or government authorities or agencies in the UAE. Accordingly, this Prospectus does not constitute an invitation or an offer of securities in the UAE (including the Dubai International Financial Centre and Abu Dhabi Global Market), and may not and will not imply any intention to either, and hence should not be construed to be any such offer of securities in the UAE. This Prospectus is only being presented and disseminated to a limited number of Institutional/sophisticated subscribers upon their request and on their understanding of the aforementioned non-registration with any UAE authorities of this Offering. This Offering is not for circulation to the general public in the UAE and may not be reproduced or used for any other purpose.',
  'United Kingdom': 'For the purposes of prospective Subscribers in the United Kingdom, this Prospectus and information contained herein is being made to and directed only at persons who:\n' +
  '. Have professional experience of participating in unregulated schemes falling within Article 14 (investment professionals) of the Financial Services and Markets Act 2000 (Promotion of CIS) (Exemptions) Order 2001 (the CIS Order) and fall within Article 19 (investment professionals) of the Financial Services and Markets Act 2000 (Financial Promotion) Order 2005, as amended (the FPO);\n' +
  '. Fall within Article 22(2)(a) to (d) (high net worth companies, unincorporated associations, etc.) of the CIS Order and Article 49(2)(a) to (d) (high net worth companies, unincorporated associations, etc.) of the FPO; or \n' +
  '. Persons to whom this report may otherwise be lawfully made to or directed at.',
  'Canada': 'This Prospectus is not, and may not be construed in any form or circumstance as, a prospectus, advertisement or a public offering of PLY Tokens in Canada. This Prospectus constitutes an offering of PLY Tokens only in those jurisdictions and to those persons where and to whom they may lawfully be offered for sale, and therein only by persons permitted to sell the PLY Tokens.\n' +
  '\n' +
  'No securities commission or similar authority has received, reviewed, approved or in any other manner acknowledged or accredited this Offering or Prospectus in Canada, and no attempt may be made to represent to anyone anything contrary to such. No such authority has commented on the merits (or otherwise) of the PLY Tokens, and any representation to the contrary shall constitute a misrepresentation and an offence.\n' +
  '\n' +
  'Purchasers’ representations, covenants and resale restrictions Confirmations of the acceptance of offers to purchase PLY tokens will be sent to purchasers in Canada who have not withdrawn their offers to purchase prior To the issuance of such confirmations. \n' +
  '\n' +
  'The distribution of PLY Tokens in Canada is being made on a private placement basis to residents of Ontario, Québec, British Columbia and Alberta (together the “Canada Territories”) and is accordingly exempt from the requirements in the Canada Territories that the issuer file a duly prepared and valid prospectus with the relevant securities regulatory authorities. Each Subscriber of PLY Tokens in Canada shall represent that they are a person or company or entity to which PLY Tokens may be sold without the benefit of a prospectus qualified under applicable provincial securities laws. Subscribers resident in Ontario represent to the Issuer that the purchaser is an “accredited investor” as such term is defined in Section 1.1 of National Instrument 45-106- prospectus and registration exemptions of the Canadian Securities Administrators, and the Subscriber shall be required to acquire such Tokens only as a principal. \n' +
  '\n' +
  'Subscribers to PLY Tokens should refer to the applicable provisions of the securities legislation pursuant to Canada and the relevant Canada Territories to them for the complete articles pertaining to their rights and/or consult with a competent legal advisor. Any resale of the PLY Tokens shall be required to be made in accordance with applicable securities laws which may require resales to be made in accordance with exemptions from registration and prospectus requirements. Subscribers in Canada are requested and expected to seek legal advice prior to any resale of their PLY Tokens. The Issuer is not a “reporting issuer” as such term is defined under applicable Canadian securities legislation, in any province or territory of Canada in which the PLY tokens will be offered.',
  'European Economic Area': 'This Prospectus does not constitute a sales or marketing or securities offering prospectus for the purposes of the European Union’s directive 2003/71/EC (as amended, including by directive 2010/73/EU) (the ‘Directive’) and as implemented among the member states (each a ‘State’) of the European Economic Area (the ‘EEA’). This Prospectus has been prepared on the basis that it shall not be offered or promoted unless pursuant to an exemption or non-requirement to register this prospectus with relevant EEA or State laws and regulators under the requirements of this Directive, and none of the Issuer, GP, Manager or Advisor has authorized nor does authorize any action to the contrary or where such requirement then arises to file this Prospectus with such EEA and State authorities under this Directive.\n' +
  '\n' +
  'In relation to each State, no offer of PLY tokens has been, or will be presented into the public domain in that State, other than under the following exemptions under the Directive: \n' +
  '\n' +
  'I. To any legal entity which is deemed to be a qualified investor as defined in the Directive; \n' +
  'II. To fewer than 150 natural or legal persons (other than qualified investors as defined in the Directive); or \n' +
  'III. In any other circumstances falling within article 3(2) of the prospectus Directive.\n' +
  '\n' +
  'Provided that no such offer of PLY tokens referred to in (I) to (III) above shall result in a requirement for the Issuer to publish a prospectus pursuant to Article 3 of the Directive, or supplement a prospectus pursuant to article 16 of the Directive.\n' +
  '\n' +
  'The expression \'offer of PLY tokens presented into the public domain\' in relation to any PLY Tokens in any State means the dissemination in any form and by any means of sufficient information on the terms of the Offering and the PLY Tokens to be offered so as to enable a prospective Subscriber to determine affirmatively that they shall acquire PLY Tokens.',
  'United States of America': 'The Interests referred to herein have not been and will not be registered under the Securities Act, or the laws of any state, and may not be offered or sold within the United States except pursuant to an exemption from, or in a transaction not subject to, the registration requirements of the Securities Act and applicable state laws. This Prospectus is not being made available, directly or indirectly, in or into or by use of the mails or by means of instrumentality (including without limitation, facsimile or email, telex or telephone) of interstate or foreign commerce, or of any facility of a national securities exchange, of the United States. The Interests have not been and will not be registered under the Securities Act, or the securities laws of any state or political sub-division of the United States and may not be offered, sold, transferred or delivered, directly or indirectly, in the United States or to, or for the account or benefit of, US Persons (as defined in Regulation S) except in certain transactions exempt from the registration requirements of the Securities Act and such state or other securities laws.  The securities referred to herein are being offered only outside the United States in offshore transactions in reliance on Regulation S, to investors who are not US Persons (as defined in Regulation S).',
  'Pakistan': 'This Offering and its Prospectus has not been and will not be submitted to, nor registered with or approved by, the Securities and Exchange Commission of Pakistan (such term herein including any and all other financial regulators and relevant governing bodies in Pakistan). This Offering constitutes an offer of securities in jurisdictions and to persons where and to whom the PLY Tokens may lawfully be offered for sale under relevant private placement exemptions laws allowing this Prospectus and all materials not to have to be filed with nor approved by relevant securities authorities, including the Securities and Exchange Commission of Pakistan, and therefore not subject to any securities acts and laws. This Prospectus and the Offering does not constitute an offer to subscribe for securities except to the extent permitted by the laws of each applicable jurisdiction of relevance to each Subscriber individually. Certain restrictions pertaining to the number of Subscribers to the PLY Tokens, their individual net worth or company total assets and size of investment in the Offering in order for them to meet with such securities laws exemptions which are applicable may apply. Subscribers which do not meet relevant legal exemption criteria will be rejected and any deposits (if received) shall be returned to them.',
  'Default': 'This Offering and its Prospectus constitutes an offer of securities in jurisdictions and to persons where and to whom the PLY Tokens may lawfully be offered for sale under relevant private placement exemptions laws allowing this Prospectus and all materials not to have to be filed with nor approved by relevant securities authorities, and therefore not subject to any securities acts and laws. This Prospectus and the Offering does not constitute an offer to subscribe for securities except to the extent permitted by the laws of each applicable jurisdiction of relevance to each Subscriber individually. Certain restrictions pertaining to the number of Subscribers to the PLY Tokens, their individual net worth or company total assets and size of investment in the Offering in order for them to meet with such securities laws exemptions which are applicable may apply. Subscribers which do not meet relevant legal exemption criteria will be rejected and any deposits (if received) shall be returned to them.',

};

